"""added auto increment to id of user_book model

Revision ID: 08a03cde8c4e
Revises: d98aa4c658ee
Create Date: 2024-02-07 22:39:42.622158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08a03cde8c4e'
down_revision: Union[str, None] = 'd98aa4c658ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
