"""Renamed user_book state column to status

Revision ID: 1a28ec24aff7
Revises: a5b7acdee7fe
Create Date: 2024-02-04 15:38:22.282270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1a28ec24aff7'
down_revision: Union[str, None] = 'a5b7acdee7fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_book', sa.Column('status', sa.String(length=20), nullable=True))
    op.drop_column('user_book', 'state')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_book', sa.Column('state', mysql.VARCHAR(length=20), nullable=True))
    op.drop_column('user_book', 'status')
    # ### end Alembic commands ###
