"""added id column also as primary key in user_book model

Revision ID: d98aa4c658ee
Revises: 1a28ec24aff7
Create Date: 2024-02-07 21:55:06.327356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd98aa4c658ee'
down_revision: Union[str, None] = '1a28ec24aff7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_book', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_book', 'id')
    # ### end Alembic commands ###
